/*
 * data.js — dhp都市開発 GP ホテル・リゾート関連 案件データ
 *（唯一の情報源 / single source of truth）
 *
 * カテゴリーは進行状況（進行中 / 完了）で分類。
 * 各案件は詳細ページ（project.html?id=...）で landArea / plan / story /
 * gallery（写真） / documents（資料）まで表示します。
 * このファイルは admin.html から書き出して差し替えできます。
 * 手で編集する場合も CLAUDE.md のデータ構造を厳守してください。
 */
const SITE_DATA = {
  categories: [
    { id: "ongoing", ja: "進行中", en: "In progress" },
    { id: "completed", ja: "完了", en: "Completed" }
  ],
  projects: [
    {
      id: "dhp0001",
      category: "ongoing",
      image: "",
      name: { ja: "川奈リゾートホテル PJ（新規）", en: "Kawana Resort Hotel (New)" },
      location: { ja: "静岡県伊東市川奈", en: "Kawana, Ito, Shizuoka" },
      summary: { ja: "所有者と専任コンサルティング会社を通じて交渉を開始（新規案件）。", en: "Negotiations started with the owner via a dedicated consulting firm (new project)." },
      status: { ja: "交渉開始", en: "Negotiations started" },
      year: null,
      area: "",
      investment: { ja: "事業規模：協議中", en: "Project scale: under discussion" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0002",
      category: "ongoing",
      image: "",
      name: { ja: "熱海リゾートホテル PJ（新規）", en: "Atami Resort Hotel (New)" },
      location: { ja: "静岡県熱海市", en: "Atami, Shizuoka" },
      summary: { ja: "所有者と専任コンサルティング会社を通じて交渉を開始（新規案件）。", en: "Negotiations started with the owner via a dedicated consulting firm (new project)." },
      status: { ja: "交渉開始", en: "Negotiations started" },
      year: null,
      area: "",
      investment: { ja: "事業規模：協議中", en: "Project scale: under discussion" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0003",
      category: "ongoing",
      image: "",
      name: { ja: "京都哲学の道 迎賓館 PJ", en: "Kyoto Philosopher's Path Guest House" },
      location: { ja: "京都府京都市左京区", en: "Sakyo-ku, Kyoto" },
      summary: { ja: "2026年6〜7月に土地購入予定。ファンドにて取得し、迎賓館（保養所）をシェア分譲予定。", en: "Land purchase planned for Jun–Jul 2026; to be acquired via fund and offered as a shared-ownership guest house (retreat)." },
      status: { ja: "取得準備中", en: "Acquisition in preparation" },
      year: null,
      area: "",
      investment: { ja: "事業規模：協議中", en: "Project scale: under discussion" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0004",
      category: "ongoing",
      image: "",
      name: { ja: "日光リゾートホテル PJ①（東照宮北側）", en: "Nikko Resort Hotel I (north of Toshogu)" },
      location: { ja: "栃木県日光市", en: "Nikko, Tochigi" },
      summary: { ja: "D社と共同事業で協議中。企画計画を再検討し、ホテルブランドを協議中。", en: "In discussion as a joint venture with Company D; reviewing the plan and selecting a hotel brand." },
      status: { ja: "協議中", en: "In discussion" },
      year: null,
      area: "",
      investment: { ja: "事業規模：協議中", en: "Project scale: under discussion" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0005",
      category: "ongoing",
      image: "",
      name: { ja: "日光リゾートホテル PJ②（テニスコート）", en: "Nikko Resort Hotel II (tennis court site)" },
      location: { ja: "栃木県日光市", en: "Nikko, Tochigi" },
      summary: { ja: "所有者（市）と協議予定。ライフスタイル系ホテルの誘致を予定。", en: "Discussions planned with the owner (city); aiming to attract a lifestyle hotel brand." },
      status: { ja: "協議予定", en: "Discussion planned" },
      year: null,
      area: "",
      investment: { ja: "事業規模：未定", en: "Project scale: TBD" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0006",
      category: "ongoing",
      image: "",
      name: { ja: "日光YH リニューアル PJ", en: "Nikko Youth Hostel Renewal" },
      location: { ja: "栃木県日光市", en: "Nikko, Tochigi" },
      summary: { ja: "所有者（地元企業）と協議開始。ファンドにて取得し、ユースホステルからレストラン・バー・温浴施設へリニューアル計画。", en: "Discussions started with the owner (local company); to be acquired via fund and renovated from a youth hostel into restaurant, bar and spa facilities." },
      status: { ja: "協議開始", en: "Discussion started" },
      year: null,
      area: "",
      investment: { ja: "約20億円", en: "approx. ¥2.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0007",
      category: "ongoing",
      image: "",
      name: { ja: "伊丹コンフォルトホテル リブランド PJ", en: "Itami Comfort Hotel Rebrand" },
      location: { ja: "兵庫県伊丹市", en: "Itami, Hyogo" },
      summary: { ja: "所有者（地元企業）と協議開始。ファンドで取得し、全43室を全面リニューアル。BWH WHクラフテッドを誘致予定。", en: "Discussions started with the owner (local company); to be acquired via fund and fully renovated (43 rooms). Plan to introduce BWH WorldHotels Crafted." },
      status: { ja: "協議開始", en: "Discussion started" },
      year: null,
      area: "43室 / 43 rooms",
      investment: { ja: "約30億円（事業希望）", en: "approx. ¥3.0B (target)" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0008",
      category: "ongoing",
      image: "",
      name: { ja: "大阪北区西天満 エンターテイメントホテル PJ", en: "Osaka Nishi-Tenma Entertainment Hotel" },
      location: { ja: "大阪府大阪市北区西天満", en: "Nishi-Tenma, Kita-ku, Osaka" },
      summary: { ja: "土地所有者（KTV・借地希望）。D社と共同でエンターテイメントホテルを企画計画中。BWH WHクラフティッドを誘致予定。", en: "Land owner (KTV, seeking leasehold). Planning an entertainment hotel jointly with Company D; plan to introduce BWH WorldHotels Crafted." },
      status: { ja: "計画中", en: "In planning" },
      year: null,
      area: "",
      investment: { ja: "事業規模：未定（計画中）", en: "Project scale: TBD (in planning)" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0009",
      category: "ongoing",
      image: "",
      name: { ja: "山梨県勝沼ワイナリーホテル PJ", en: "Yamanashi Katsunuma Winery Hotel" },
      location: { ja: "山梨県甲州市勝沼", en: "Katsunuma, Koshu, Yamanashi" },
      summary: { ja: "会社買収（M&A）形式で2026年3月に法人取得済。ホテル計画策定中（40㎡・80室前後）。ホテルブランド協議予定。", en: "Entity acquired via M&A in Mar 2026. Hotel planning underway (approx. 40㎡ rooms, ~80 keys); brand discussions to follow." },
      status: { ja: "法人取得済・計画中", en: "Entity acquired, in planning" },
      year: null,
      area: "80室前後 / approx. 80 rooms",
      investment: { ja: "約150〜200億円", en: "approx. ¥15–20B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0010",
      category: "ongoing",
      image: "",
      name: { ja: "湯田中温泉 保養所リブランド PJ", en: "Yudanaka Onsen Retreat Rebrand" },
      location: { ja: "長野県下高井郡山ノ内町（湯田中）", en: "Yamanouchi (Yudanaka), Nagano" },
      summary: { ja: "SPCにて物件取得済、改装計画中。和風旅館18室をBWHブランドで誘致予定（自社GP事業）。", en: "Property acquired via SPC; renovation underway. 18-room ryokan to introduce a BWH brand (dhp GP project)." },
      status: { ja: "取得済・改装計画中", en: "Acquired, renovation planning" },
      year: null,
      area: "和風旅館18室 / 18-room ryokan",
      investment: { ja: "約6億円", en: "approx. ¥0.6B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0011",
      category: "ongoing",
      image: "",
      name: { ja: "名古屋駅前 ライフスタイルホテル PJ", en: "Nagoya Station-front Lifestyle Hotel" },
      location: { ja: "愛知県名古屋市", en: "Nagoya, Aichi" },
      summary: { ja: "dhp都市開発が用地取り纏め（地上げ）中、2026年5〜6月完了予定。ライフスタイルホテルを計画、BWHブランド誘致予定。", en: "dhp is assembling the land (completion Jun 2026). Planning a lifestyle hotel; plan to introduce a BWH brand." },
      status: { ja: "用地取り纏め中", en: "Land assembly underway" },
      year: null,
      area: "",
      investment: { ja: "約120億円", en: "approx. ¥12B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0012",
      category: "ongoing",
      image: "",
      name: { ja: "中軽井沢駅前 ライフスタイルホテル PJ", en: "Naka-Karuizawa Station-front Lifestyle Hotel" },
      location: { ja: "長野県北佐久郡軽井沢町", en: "Karuizawa, Nagano" },
      summary: { ja: "地主と土地取得協議中（価格交渉難航）。開発許可取得済。ライフスタイルホテル約60室。", en: "Land acquisition in discussion (pricing challenging). Development permit obtained. Lifestyle hotel, ~60 rooms." },
      status: { ja: "取得協議中", en: "Acquisition in discussion" },
      year: null,
      area: "約60室 / approx. 60 rooms",
      investment: { ja: "事業規模：未定", en: "Project scale: TBD" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0013",
      category: "ongoing",
      image: "",
      name: { ja: "熱海 木宮駅前 スモールラグジュアリーホテル PJ", en: "Atami Kinomiya Station-front Small Luxury Hotel" },
      location: { ja: "静岡県熱海市", en: "Kinomiya, Atami, Shizuoka" },
      summary: { ja: "土地取得協議中。ホテル企画設計中（55㎡・54室）。ブランド選定協議中。", en: "Land acquisition in discussion. Hotel design underway (55㎡ rooms, 54 keys); brand selection ongoing." },
      status: { ja: "取得協議・設計中", en: "Acquisition & design" },
      year: null,
      area: "54室 / 54 rooms",
      investment: { ja: "約100億円", en: "approx. ¥10B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0014",
      category: "ongoing",
      image: "",
      name: { ja: "函館 KOKOホテル PJ", en: "Hakodate KOKO Hotel" },
      location: { ja: "北海道函館市", en: "Hakodate, Hokkaido" },
      summary: { ja: "T社ほかへの売却で協議中。設計・ゼネコンと協議中。", en: "In discussion to sell to Company T and others; coordinating design and general contractor." },
      status: { ja: "売却協議中", en: "Sale in discussion" },
      year: null,
      area: "",
      investment: { ja: "約50億円", en: "approx. ¥5.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0015",
      category: "ongoing",
      image: "",
      name: { ja: "「由布院 森のテラス」オーベルジュ PJ", en: "\"Yufuin Mori no Terrace\" Auberge" },
      location: { ja: "大分県由布市湯布院町", en: "Yufuin, Oita" },
      summary: { ja: "土地取得交渉中。ファンドにて取得予定。既存16室＋ヴィラ14棟を計画。BWH WHを誘致予定。", en: "Land acquisition under negotiation; to be acquired via fund. Plan for 16 existing rooms + 14 villas; to introduce BWH WorldHotels." },
      status: { ja: "取得交渉中", en: "Acquisition negotiation" },
      year: null,
      area: "16室＋ヴィラ14棟 / 16 rooms + 14 villas",
      investment: { ja: "約20億円", en: "approx. ¥2.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0016",
      category: "ongoing",
      image: "",
      name: { ja: "「七色の風」オーベルジュ PJ", en: "\"Nanairo no Kaze\" Auberge" },
      location: { ja: "所在地調整中", en: "Location TBD" },
      summary: { ja: "土地取得（M&A）の優先交渉権を取得。既存解体＋ホテル棟24室＋ヴィラ6棟を計画中。BWH WHクラフティッド誘致決定。", en: "Secured preferred negotiation rights (M&A). Plan to demolish existing and build a 24-room hotel + 6 villas; BWH WorldHotels Crafted confirmed." },
      status: { ja: "優先交渉権取得", en: "Preferred rights secured" },
      year: null,
      area: "24室＋ヴィラ6棟 / 24 rooms + 6 villas",
      investment: { ja: "約75億円", en: "approx. ¥7.5B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0017",
      category: "ongoing",
      image: "",
      name: { ja: "旧軽井沢倶楽部 倶楽部ハウス PJ", en: "Kyu-Karuizawa Club – Clubhouse" },
      location: { ja: "長野県北佐久郡軽井沢町", en: "Karuizawa, Nagano" },
      summary: { ja: "所有者（地元企業）と協議中。旧軽井沢倶楽部内のヴィラ用地も併せて取得検討。レストラン＋ゲストハウスへリニューアル予定。", en: "In discussion with the owner (local company); also considering villa land within the Kyu-Karuizawa Club. To be renovated into a restaurant + guesthouse." },
      status: { ja: "協議中", en: "In discussion" },
      year: null,
      area: "",
      investment: { ja: "約30億円＋ヴィラ用地10〜15億円", en: "approx. ¥3.0B + villa land ¥1.0–1.5B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0018",
      category: "ongoing",
      image: "",
      name: { ja: "軽井沢南原 ブランデッドリゾートレジデンス PJ", en: "Karuizawa Minamihara Branded Resort Residence" },
      location: { ja: "長野県北佐久郡軽井沢町南原", en: "Minamihara, Karuizawa, Nagano" },
      summary: { ja: "地主と土地取得協議中。企画設計開始。200㎡強・14戸で計画。", en: "Land acquisition in discussion; design started. Plan for 14 units of 200㎡+." },
      status: { ja: "取得協議・設計中", en: "Acquisition & design" },
      year: null,
      area: "14戸 / 14 units",
      investment: { ja: "約120〜150億円", en: "approx. ¥12–15B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0019",
      category: "ongoing",
      image: "",
      name: { ja: "奄美大島 龍郷リゾートホテル開発 PJ", en: "Amami Oshima Tatsugo Resort Hotel" },
      location: { ja: "鹿児島県大島郡龍郷町", en: "Tatsugo, Amami, Kagoshima" },
      summary: { ja: "所有者（個人）＋専任プロジェクトアレンジャーと協議開始。秋に用地取得予定。リゾートホテル（50㎡・60室前後）を検討、ブランド協議予定。", en: "Discussions started with the owner (individual) and a dedicated project arranger; land acquisition planned for autumn. Considering a resort hotel (50㎡ rooms, ~60 keys); brand discussions to follow." },
      status: { ja: "協議開始", en: "Discussion started" },
      year: null,
      area: "60室前後 / approx. 60 rooms",
      investment: { ja: "約150億円", en: "approx. ¥15B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0020",
      category: "ongoing",
      image: "",
      name: { ja: "和歌山白浜町 古ホテル再開発 PJ", en: "Wakayama Shirahama Former Hotel Redevelopment" },
      location: { ja: "和歌山県西牟婁郡白浜町", en: "Shirahama, Wakayama" },
      summary: { ja: "所有者（K社）と取得交渉開始。リゾートホテルを企画計画中（36㎡・44㎡、69室前後）。ブランド協議開始。", en: "Acquisition negotiations started with Company K. Planning a resort hotel (36/44㎡ rooms, ~69 keys); brand discussions started." },
      status: { ja: "取得交渉開始", en: "Acquisition negotiation started" },
      year: null,
      area: "69室前後 / approx. 69 rooms",
      investment: { ja: "約80億円", en: "approx. ¥8.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0021",
      category: "ongoing",
      image: "",
      name: { ja: "和歌山白浜町 廃ホテル再開発 PJ", en: "Wakayama Shirahama Abandoned Hotel Redevelopment" },
      location: { ja: "和歌山県西牟婁郡白浜町", en: "Shirahama, Wakayama" },
      summary: { ja: "所有者（M社）とホテル計画の協力体制を協議済。企画計画・行政協議を開始も難航中。", en: "Agreed on a cooperation framework with Company M. Planning and administrative talks started but challenging." },
      status: { ja: "行政協議中（難航）", en: "Administrative talks (challenging)" },
      year: null,
      area: "",
      investment: { ja: "事業規模：未定", en: "Project scale: TBD" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0022",
      category: "ongoing",
      image: "",
      name: { ja: "熱海リゾートホテル PJ（100室）", en: "Atami Resort Hotel (100 rooms)" },
      location: { ja: "静岡県熱海市", en: "Atami, Shizuoka" },
      summary: { ja: "土地保有法人と協議中。ホテル企画計画、ブランド協議中（100室）。", en: "In discussion with the landholding entity. Hotel planning and brand discussions underway (100 rooms)." },
      status: { ja: "協議中", en: "In discussion" },
      year: null,
      area: "100室 / 100 rooms",
      investment: { ja: "約300億円", en: "approx. ¥30B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0023",
      category: "ongoing",
      image: "",
      name: { ja: "飛騨高山リゾートホテル PJ", en: "Hida-Takayama Resort Hotel" },
      location: { ja: "岐阜県高山市", en: "Takayama, Gifu" },
      summary: { ja: "土地契約締結済。ホテル企画計画、ブランド選定中（Mギャラリー内諾取得済、108室）。", en: "Land contract signed. Hotel planning and brand selection underway (MGallery in-principle agreement obtained, 108 rooms)." },
      status: { ja: "土地契約済・設計中", en: "Land contracted, in design" },
      year: null,
      area: "108室 / 108 rooms",
      investment: { ja: "約250億円", en: "approx. ¥25B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0024",
      category: "ongoing",
      image: "",
      name: { ja: "奄美大島リゾートホテル PJ（ヴィラ82棟）", en: "Amami Oshima Resort Hotel (82 villas)" },
      location: { ja: "鹿児島県奄美市", en: "Amami, Kagoshima" },
      summary: { ja: "土地優先交渉権を取得し協定書締結。共同投資家と協議中（5つ星・ヴィラホテル82棟）。ブランド選定中（ヒルトン系・アコー系）。", en: "Secured land rights and signed an MOU. In discussion with co-investors (5-star villa hotel, 82 villas); brand selection underway (Hilton/Accor)." },
      status: { ja: "優先交渉権取得・協定締結", en: "Rights secured, MOU signed" },
      year: null,
      area: "ヴィラ82棟 / 82 villas",
      investment: { ja: "約250億円", en: "approx. ¥25B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0025",
      category: "ongoing",
      image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      name: { ja: "六本木4丁目ホテル PJ", en: "Roppongi 4-chome Hotel" },
      location: { ja: "東京都港区六本木", en: "Roppongi, Minato-ku, Tokyo" },
      summary: { ja: "土地所有者と協議中、事業主と協定書締結。国内大手デベロッパーと共同事業形式でホテル＋レジデンス開発計画が進行中（ヒルトンLXRほか、ホテル約90室＋ブランデッドレジデンス約76戸）。", en: "In discussion with the land owner; MOU signed with the operator. Hotel + residence development progressing as a JV with a major domestic developer (Hilton LXR etc., ~90 rooms + ~76 branded residences)." },
      status: { ja: "協定締結・進行中", en: "MOU signed, in progress" },
      year: null,
      area: "ホテル約90室＋レジデンス76戸 / ~90 rooms + 76 residences",
      investment: { ja: "約1,300億円〜", en: "approx. ¥130B+" },
      landArea: "",
      plan: { ja: "国内大手デベロッパーとの共同事業によるホテル＋ブランデッドレジデンスの複合開発。ヒルトンLXRほかを軸に、ホテル約90室・レジデンス約76戸を計画。", en: "A mixed-use hotel + branded residence development as a JV with a major domestic developer. Centered on Hilton LXR and others, planned for ~90 hotel rooms and ~76 residences." },
      story: { ja: "土地所有者との協議と事業主との協定書締結を経て、都心一等地での超高級ホテル＆レジデンス計画が進行中。事業規模は約1,300億円〜。", en: "Following discussions with the land owner and an MOU with the operator, an ultra-luxury hotel & residence plan in a prime central Tokyo location is progressing, with a project scale of approx. ¥130B+." },
      gallery: [
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80"
      ],
      documents: []
    },
    {
      id: "dhp0026",
      category: "ongoing",
      image: "",
      name: { ja: "旧軽井沢 高級リゾートレジデンス PJ", en: "Kyu-Karuizawa Luxury Resort Residence" },
      location: { ja: "長野県北佐久郡軽井沢町", en: "Karuizawa, Nagano" },
      summary: { ja: "SPCにて土地取得済。ブランディッド高級リゾートレジデンスを企画設計中（40戸）。", en: "Land acquired via SPC. Branded luxury resort residence in design (40 units)." },
      status: { ja: "取得済・設計中", en: "Acquired, in design" },
      year: null,
      area: "40戸 / 40 units",
      investment: { ja: "約150億円", en: "approx. ¥15B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0027",
      category: "ongoing",
      image: "",
      name: { ja: "宮古島砂山リゾートホテル PJ②", en: "Miyakojima Sunayama Resort Hotel II" },
      location: { ja: "沖縄県宮古島市", en: "Miyakojima, Okinawa" },
      summary: { ja: "地主（エリア1）と売買契約締結済。ホテル企画計画作成中。Marriott（107室＋ヴィラ20棟）またはフォーシーズンズ（ヴィラ85棟）で検討中。", en: "Purchase contract signed with the landowner (Area 1). Planning underway; considering Marriott (107 rooms + 20 villas) or Four Seasons (85 villas)." },
      status: { ja: "売買契約済・計画中", en: "Purchase contracted, in planning" },
      year: null,
      area: "107室＋ヴィラ20棟 / 107 rooms + 20 villas",
      investment: { ja: "約400億円", en: "approx. ¥40B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0028",
      category: "ongoing",
      image: "",
      name: { ja: "宮古島砂山リゾートヴィラ PJ③", en: "Miyakojima Sunayama Resort Villa III" },
      location: { ja: "沖縄県宮古島市", en: "Miyakojima, Okinawa" },
      summary: { ja: "地主と協定書締結済。ホテル・ヴィラ・商業施設を企画計画中（エリア4・5）。ホテルブランドはOWで内定。", en: "MOU signed with the landowner. Planning hotel, villas and retail (Areas 4 & 5); hotel brand tentatively decided as OW." },
      status: { ja: "協定締結済・計画中", en: "MOU signed, in planning" },
      year: null,
      area: "",
      investment: { ja: "事業規模：計画中", en: "Project scale: in planning" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0029",
      category: "ongoing",
      image: "",
      name: { ja: "宮古島砂山リゾートホテル PJ④", en: "Miyakojima Sunayama Resort Hotel IV" },
      location: { ja: "沖縄県宮古島市", en: "Miyakojima, Okinawa" },
      summary: { ja: "地主と協定書締結を協議中。ホテル・ヴィラを企画計画予定（エリア3）。ホテルブランド誘致予定。", en: "MOU under discussion with the landowner. Hotel and villas planning to follow (Area 3); brand to be introduced." },
      status: { ja: "協定協議中", en: "MOU under discussion" },
      year: null,
      area: "",
      investment: { ja: "事業規模：協議中", en: "Project scale: under discussion" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0030",
      category: "ongoing",
      image: "",
      name: { ja: "大阪宗右衛門町ホテル PJ", en: "Osaka Soemoncho Hotel" },
      location: { ja: "大阪府大阪市中央区宗右衛門町", en: "Soemoncho, Chuo-ku, Osaka" },
      summary: { ja: "ハードロックホテルで計画中、LOI取得済。行政協議完了（客室205室・レジデンス113室）。", en: "Planning a Hard Rock Hotel, LOI secured. Approvals completed (205 rooms + 113 residences)." },
      status: { ja: "LOI取得・行政協議完了", en: "LOI secured, approvals completed" },
      year: null,
      area: "客室205室＋レジデンス113室 / 205 rooms + 113 residences",
      investment: { ja: "1,200億円から", en: "from approx. ¥120B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0031",
      category: "ongoing",
      image: "",
      name: { ja: "箱根ランド リゾートホテル PJ", en: "Hakone Land Resort Hotel" },
      location: { ja: "神奈川県足柄下郡箱根町", en: "Hakone, Kanagawa" },
      summary: { ja: "地主（行政）・借地人（ホテル廃業済）と借地権取得を協議・調整中。5つ星ホテルブランド誘致予定。", en: "Negotiating leasehold acquisition with the landowner (government) and lessee (former hotel). Plan to introduce a 5-star hotel brand." },
      status: { ja: "借地権取得協議中", en: "Leasehold negotiation" },
      year: null,
      area: "",
      investment: { ja: "事業規模：未定", en: "Project scale: TBD" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0032",
      category: "ongoing",
      image: "",
      name: { ja: "恩納村瀬良垣リゾートホテル PJ", en: "Onna Seragaki Resort Hotel" },
      location: { ja: "沖縄県国頭郡恩納村瀬良垣", en: "Seragaki, Onna, Okinawa" },
      summary: { ja: "地主（K-AM社）と協定書締結。設計変更およびヒルトン社と協議し、ブランド決定（200室）。", en: "MOU signed with the landowner (K-AM). Design revisions and talks with Hilton completed; brand decided (200 rooms)." },
      status: { ja: "協定締結・ブランド決定", en: "MOU signed, brand decided" },
      year: null,
      area: "200室 / 200 rooms",
      investment: { ja: "約400億円", en: "approx. ¥40B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0033",
      category: "ongoing",
      image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
      name: { ja: "鳥取砂丘リゾートホテル PJ", en: "Tottori Sand Dunes Resort Hotel" },
      location: { ja: "鳥取県鳥取市", en: "Tottori, Tottori" },
      summary: { ja: "鳥取市のプロポーザル入札。開発許可・建築確認取得済。Marriott Luxury Collection（108室）。", en: "Won Tottori City proposal tender. Development and building permits obtained. Marriott Luxury Collection (108 rooms)." },
      status: { ja: "許認可取得済", en: "Permits obtained" },
      year: null,
      area: "108室 / 108 rooms",
      investment: { ja: "約285億円", en: "approx. ¥28.5B" },
      landArea: "",
      plan: { ja: "鳥取市のプロポーザルにより事業者選定。開発許可・建築確認を取得済。Marriott Luxury Collection（108室）として計画。", en: "Selected via Tottori City's proposal process. Development and building permits obtained. Planned as a Marriott Luxury Collection (108 rooms)." },
      story: { ja: "", en: "" },
      gallery: [
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80"
      ],
      documents: []
    },
    {
      id: "dhp0034",
      category: "ongoing",
      image: "",
      name: { ja: "奄美大島リゾートホテル PJ（20室・自社GP）", en: "Amami Oshima Resort Hotel (20 rooms, GP)" },
      location: { ja: "鹿児島県奄美市", en: "Amami, Kagoshima" },
      summary: { ja: "事業パートナー会社が土地契約済。ホテル計画作成・設計中（20室、自社GP事業）。", en: "Business partner has contracted the land. Hotel planning and design underway (20 rooms, dhp GP project)." },
      status: { ja: "土地契約済・設計中", en: "Land contracted, in design" },
      year: null,
      area: "20室 / 20 rooms",
      investment: { ja: "約50億円", en: "approx. ¥5.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0035",
      category: "ongoing",
      image: "",
      name: { ja: "鳥取県大山ホテル ミニPJ", en: "Tottori Daisen Mini Hotel" },
      location: { ja: "鳥取県西伯郡大山町", en: "Daisen, Tottori" },
      summary: { ja: "地主（伊丹学園）と共同事業。ホテル・ヴィラ計画作成中（20室、自社GP事業）。", en: "JV with the landowner (Itami Gakuen). Hotel and villa planning underway (20 rooms, dhp GP project)." },
      status: { ja: "共同事業・計画中", en: "JV, in planning" },
      year: null,
      area: "20室 / 20 rooms",
      investment: { ja: "約30億円", en: "approx. ¥3.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0036",
      category: "ongoing",
      image: "",
      name: { ja: "奈良市三条ホテル PJ", en: "Nara Sanjo Hotel" },
      location: { ja: "奈良県奈良市三条", en: "Sanjo, Nara" },
      summary: { ja: "土地賃貸借契約済。Marriott MOXY。開発許可・建築確認取得済（138室）。", en: "Land lease signed. Marriott Moxy. Development and building permits obtained (138 rooms)." },
      status: { ja: "賃貸借契約済・許認可取得", en: "Lease signed, permits obtained" },
      year: null,
      area: "138室 / 138 rooms",
      investment: { ja: "約60億円", en: "approx. ¥6.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0037",
      category: "ongoing",
      image: "",
      name: { ja: "石垣島川平 ミニホテル PJ", en: "Ishigaki Kabira Mini Hotel" },
      location: { ja: "沖縄県石垣市川平", en: "Kabira, Ishigaki, Okinawa" },
      summary: { ja: "土地取得済（一部賃貸借）。ミニホテル20室を計画、開発許可取得済（E社と共同事業）。", en: "Land acquired (partly leased). Mini hotel of 20 rooms planned; development permit obtained (JV with Company E)." },
      status: { ja: "取得済・許可取得", en: "Acquired, permit obtained" },
      year: null,
      area: "20室 / 20 rooms",
      investment: { ja: "約40億円", en: "approx. ¥4.0B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0038",
      category: "ongoing",
      image: "",
      name: { ja: "石垣島リゾートヴィラ PJ", en: "Ishigaki Resort Villa" },
      location: { ja: "沖縄県石垣市", en: "Ishigaki, Okinawa" },
      summary: { ja: "ヴィラ6棟の計画プラン作成。先行2棟竣工済、売却予定（残4区画、dhp自社事業）。", en: "Plan for 6 villas; first 2 completed and for sale (4 lots remaining, dhp own project)." },
      status: { ja: "一部竣工・売却予定", en: "Partly completed, for sale" },
      year: null,
      area: "ヴィラ6棟 / 6 villas",
      investment: { ja: "約15億円", en: "approx. ¥1.5B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0039",
      category: "ongoing",
      image: "",
      name: { ja: "平戸グランピング PJ", en: "Hirado Glamping" },
      location: { ja: "長崎県平戸市", en: "Hirado, Nagasaki" },
      summary: { ja: "土地契約締結済。グランピング・ヴィラを企画計画中（事業一時中断中、自社GP事業）。", en: "Land contract signed. Glamping and villas in planning (temporarily on hold, dhp GP project)." },
      status: { ja: "契約済・一時中断", en: "Contracted, on hold" },
      year: null,
      area: "",
      investment: { ja: "事業規模：未定", en: "Project scale: TBD" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0040",
      category: "ongoing",
      image: "",
      name: { ja: "沖縄美ら海ヴィラ PJ", en: "Okinawa Churaumi Villa" },
      location: { ja: "沖縄県国頭郡本部町", en: "Motobu, Okinawa" },
      summary: { ja: "ヴィラ4棟。土地取得済、里道払下げ完了。ヴィラプラン作成中（自社GP事業）。", en: "4 villas. Land acquired and public-road transfer completed; villa plan underway (dhp GP project)." },
      status: { ja: "取得済・計画中", en: "Acquired, in planning" },
      year: null,
      area: "ヴィラ4棟 / 4 villas",
      investment: { ja: "事業規模：計画中", en: "Project scale: in planning" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0041",
      category: "ongoing",
      image: "",
      name: { ja: "香川県小豆島コテージ PJ", en: "Kagawa Shodoshima Cottage" },
      location: { ja: "香川県小豆郡（小豆島）", en: "Shodoshima, Kagawa" },
      summary: { ja: "土地取得済。コテージ10棟を計画中（自社GP事業）。", en: "Land acquired. Planning 10 cottages (dhp GP project)." },
      status: { ja: "取得済・計画中", en: "Acquired, in planning" },
      year: null,
      area: "コテージ10棟 / 10 cottages",
      investment: { ja: "事業規模：計画中", en: "Project scale: in planning" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0042",
      category: "completed",
      image: "",
      name: { ja: "奈良春日「鹿のや」PJ", en: "Nara Kasuga \"Shika-no-ya\"" },
      location: { ja: "奈良県奈良市春日", en: "Kasuga, Nara" },
      summary: { ja: "土地賃貸借契約・建築確認取得、建築工事完了。dhpリゾートにて運営（dhp自社事業）。", en: "Land lease and building permit obtained, construction completed. Operated by dhp Resort (dhp own project)." },
      status: { ja: "完成・運営中", en: "Completed, operating" },
      year: null,
      area: "",
      investment: { ja: "約6億円", en: "approx. ¥0.6B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0043",
      category: "completed",
      image: "",
      name: { ja: "軽井沢追分リゾートホテル PJ", en: "Karuizawa Oiwake Resort Hotel" },
      location: { ja: "長野県北佐久郡軽井沢町追分", en: "Oiwake, Karuizawa, Nagano" },
      summary: { ja: "土地・開発許可・建築確認を取得。Marriott Autograph Collectionブランドにてレーサム社へ売却済。", en: "Land and all permits obtained. Sold to Raysum as a Marriott Autograph Collection." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "",
      investment: { ja: "約150億円", en: "approx. ¥15B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0044",
      category: "completed",
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
      name: { ja: "宮古島砂山リゾートホテル PJ①", en: "Miyakojima Sunayama Resort Hotel I" },
      location: { ja: "沖縄県宮古島市", en: "Miyakojima, Okinawa" },
      summary: { ja: "土地約3万2000坪を取得しSPCに譲渡済。国内アパレル＋香港系企業に売却済（共同事業先の事情により土地売却のみで中断）。", en: "Acquired ~32,000 tsubo and transferred to SPC; sold to a domestic apparel firm and a Hong Kong company (halted at land sale due to JV partner circumstances)." },
      status: { ja: "売却済（土地）", en: "Sold (land)" },
      year: null,
      area: "約3万2000坪（用地） / approx. 32,000 tsubo (land)",
      investment: { ja: "約51億円（事業規模 約350億円）", en: "approx. ¥5.1B (project scale ¥35B)" },
      landArea: "約32,000坪（約105,800㎡） / approx. 32,000 tsubo (≈105,800 m²)",
      plan: { ja: "宮古島・砂山ビーチ至近の大規模リゾート用地。区画整理を経てSPCへ譲渡し、リゾートホテル開発用地として整備した。", en: "A large resort site near Sunayama Beach, Miyakojima. After land consolidation it was transferred to an SPC and prepared as a resort hotel development site." },
      story: { ja: "dhp都市開発GPが約3万2000坪の用地を取得し、SPCへ譲渡。国内アパレル企業と香港系企業へ売却した。共同事業先の事情により計画は土地売却をもって一旦中断したが、エリア全体（後続のPJ②〜④）の開発ポテンシャルを示す先行事例となった。", en: "dhp Urban Development GP acquired roughly 32,000 tsubo and transferred it to an SPC, then sold it to a domestic apparel company and a Hong Kong-based firm. Although the plan paused at the land sale due to the JV partner's circumstances, it became a pioneering case demonstrating the development potential of the wider area (later projects II–IV)." },
      gallery: [
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80"
      ],
      documents: [
        { ja: "プロジェクト概要（サンプル）", en: "Project Overview (Sample)", file: "downloads/sample-project-overview.pdf" }
      ]
    },
    {
      id: "dhp0045",
      category: "completed",
      image: "",
      name: { ja: "軽井沢リゾートホテル PJ", en: "Karuizawa Resort Hotel" },
      location: { ja: "長野県北佐久郡軽井沢町", en: "Karuizawa, Nagano" },
      summary: { ja: "開発許可・建築確認取得済。東京センチュリーに事業譲渡済（現インターコンチネンタル・インディゴ）。", en: "Development and building permits obtained. Business transferred to Tokyo Century (now InterContinental / Hotel Indigo)." },
      status: { ja: "事業譲渡済", en: "Business transferred" },
      year: null,
      area: "",
      investment: { ja: "約150億円", en: "approx. ¥15B" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0046",
      category: "completed",
      image: "",
      name: { ja: "名古屋則武ホテル PJ", en: "Nagoya Noritake Hotel" },
      location: { ja: "愛知県名古屋市西区則武", en: "Noritake, Nagoya, Aichi" },
      summary: { ja: "土地取り纏め・立ち退き買収後、事業パートナー経由でサムティへ売却済（現ニッコースタイル）。", en: "After land assembly and tenant buyout, sold to Samty via business partner (now Nikko Style)." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0047",
      category: "completed",
      image: "",
      name: { ja: "大阪曽根崎ホテル PJ", en: "Osaka Sonezaki Hotel" },
      location: { ja: "大阪府大阪市北区曽根崎", en: "Sonezaki, Kita-ku, Osaka" },
      summary: { ja: "土地買収後、企画設計を経てSGRGICに売却。最終的にアパホテル（1,500室）に売却済。", en: "After land acquisition and design, sold to SGRGIC; ultimately sold to APA Hotel (1,500 rooms)." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "1,500室 / 1,500 rooms",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0048",
      category: "completed",
      image: "",
      name: { ja: "大阪天満ホテル PJ", en: "Osaka Tenma Hotel" },
      location: { ja: "大阪府大阪市北区天満", en: "Tenma, Kita-ku, Osaka" },
      summary: { ja: "ホテル完成後、SGRファンド（NOKU）に売却済。", en: "After completion, sold to SGR fund (NOKU)." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0049",
      category: "completed",
      image: "",
      name: { ja: "名古屋つちやホテル PJ", en: "Nagoya Tsuchiya Hotel" },
      location: { ja: "愛知県名古屋市", en: "Nagoya, Aichi" },
      summary: { ja: "ホテル取得後に解体、企画設計を経てダイワハウスに売却済（ソフトウェア会社の名古屋支店）。", en: "Acquired and demolished; after design, sold to Daiwa House (a software company's Nagoya office)." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0050",
      category: "completed",
      image: "",
      name: { ja: "名古屋名駅南4丁目 PJ", en: "Nagoya Meieki-minami 4-chome" },
      location: { ja: "愛知県名古屋市中村区名駅南", en: "Meieki-minami, Nagoya, Aichi" },
      summary: { ja: "土地買収・企画設計後、東横イン（800室）・台湾企業に売却。", en: "After land acquisition and design, sold to Toyoko Inn (800 rooms) / a Taiwanese company." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "800室 / 800 rooms",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0051",
      category: "completed",
      image: "",
      name: { ja: "名古屋納谷橋ホテル PJ", en: "Nagoya Nayabashi Hotel" },
      location: { ja: "愛知県名古屋市", en: "Nagoya, Aichi" },
      summary: { ja: "土地買収・企画設計後、JR西日本都市開発に売却（くれたけ荘、146室）。", en: "After land acquisition and design, sold to JR West Urban Development (Kuretake-so, 146 rooms)." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "146室 / 146 rooms",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    },
    {
      id: "dhp0052",
      category: "completed",
      image: "",
      name: { ja: "大阪此花区 USJホテル PJ", en: "Osaka Konohana USJ Hotel" },
      location: { ja: "大阪府大阪市此花区", en: "Konohana-ku, Osaka" },
      summary: { ja: "土地取得・企画設計後、日本セレモニーに売却（現ユニバーサルポートヴィータ）。", en: "After land acquisition and design, sold to Nihon Ceremony (now Universal Port Vita)." },
      status: { ja: "売却済", en: "Sold" },
      year: null,
      area: "",
      investment: { ja: "", en: "" },
      landArea: "",
      plan: { ja: "", en: "" },
      story: { ja: "", en: "" },
      gallery: [],
      documents: []
    }
  ]
};

// ブラウザ・admin の双方から参照できるように公開する
if (typeof window !== "undefined") {
  window.SITE_DATA = SITE_DATA;
}
